name: tes Composite Action
on: [push]
jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: ls
        uses: './.github/actions/my-action'